# -*- coding: utf-8 -*-
"""Rodriguez_Scherezade_Tarea1_EDA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VifFSL80JzZtUjux2jN1kBKDIKnPWdpa
"""

# Importar las librerías necesarias
import streamlit as st
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns



# Configuración visual opcional
sns.set_style("whitegrid")
"""
# Tarea 1: Análisis Exploratorio de Datos (EDA)

**Objetivo:** Aplicar técnicas de exploración, limpieza y descripción estadística sobre un nuevo conjunto de datos.

**Instrucciones:**
1. Carga el dataset de los pasajeros del [Titanic](https://www.kaggle.com/competitions/titanic/data?select=train.csv).
2. Realiza una inspección inicial para entender la estructura de los datos.
3. Detecta y maneja datos faltantes y duplicados.
4. Extrae estadísticas descriptivas clave.
5. Escribe tus conclusiones sobre la calidad y contenido de los datos.

### 1. Carga de Datos
Carga el archivo CSV en un DataFrame de Pandas llamado `df`.
Muestra las primeras 5 filas y 5 filas aleatorias para verificar que se cargó correctamente.
"""

df = pd.read_csv('train.csv')
df      # Mostramos los datos del dataset

df.head(5)     # Muestra las 5 primeras filas

df.sample(5)         # Muestra 5 filas aleatorias

"""### 2. Inspección General
Responde a las siguientes preguntas mediante código:
* ¿Cuántas filas y columnas tiene el dataset? (`shape`)
* ¿Cuáles son los nombres de las columnas? (`columns`)
* ¿Qué tipos de datos (Dtype) tiene cada columna? (`info`)
"""

print(f"El tamaño del dataset es: {df.shape}")
print(f"Tenemos {df.shape[0]} filas y {df.shape[1]} columnas.")

"""Los nombres de las columnas, es decir, las variables son:"""

print(list(df.columns))

"""Los datos de cada columna del dataset son del tipo (int, float, object), en efecto:"""

df.info()

"""### 2.1. Diccionario de Datos (Variables)
Analicemos las variables a tratar:
* **Variables Categóricas (Cualitativas):**
    * `survival`: Indica la supervivencia del pasajero (0: No, 1:Sí)
    * `pclass`: Representa la clase del billete (1: Primera, 2: Segunda, 3: Tercera).
    * `sex`: Indica el sexo del pasajero.
    * `embarked`: Representa el puerto de embarque del pasajero (C: Cherbourg, Q: Queenstown, S: Southampton).
    * `ticket`: Se refiere al número de billete.
    * `cabin`: Indica el número de camarote

* **Variables Numéricas (Cuantitativas):**
    * `age`: Representa la edad en años del pasajero.
    * `sibsp`:  Indica el número de hermanos o cónyuges a bordo del Titanic.
    * `parch`: Indica el número de padres o hijos a bordo del Titanic.
    * `fare`:  Representa la tarifa o precio del billete pagado por el pasajero.
   

- **Peculiaridades y Reglas de Registro**:
El dataset presenta matices técnicos que deben considerarse durante la fase de limpieza y procesamiento:

  * ` Precisión de la Edad (Age)`: Se registra de forma fraccionaria si el pasajero tenía menos de un año. Además, si la edad no pudo ser confirmada y fue estimada, se utiliza el formato xx.5


  **Definición de Relaciones Familiares**

  El dataset utiliza reglas estrictas para definir quiénes cuentan como familia a bordo, lo cual es vital para entender las redes de apoyo durante el naufragio:

   * `sibsp (Hermanos / Cónyuges)`: Incluye hermanos, hermanas, hermanastros y hermanastras. En cuanto a parejas, solo contabiliza a esposos y esposas, especificando que se ignoraron a amantes y prometidos.

   * `parch (Padres / Hijos)`: Incluye relaciones biológicas y legales como madre, padre, hijos e hijastros. Una distinción importante es que si un niño viajaba únicamente con una niñera, su valor de parch es 0, ya que la variable se limita a relaciones parentales directas.

### 3. Calidad de los Datos
Antes de analizar estadísticas, debemos depurar y limpiar los datos:
1.  **Duplicados:** Verifica si hay filas duplicadas y elimínalas si existen.
"""

df.duplicated().any()    # Verificamos si existen filas duplicadas

"""Al no existir filas duplicadas, no se elimina ninguna.

2.  **Valores Nulos:** Muestra cuántos valores nulos (NaN) hay por columna.
    * *Reto:* Si encuentras nulos en variables numéricas, rellénalos con la **Mediana** (como vimos en clase para evitar sesgos por outliers).
"""

# 2 Muestra la cantidad de nulos por columna
df.isna().sum()     # isna() funcion que detecta vacios

# Una alternativa manual es usar info():
# Tamaño del dataset menos "non-null" equivale a los nulos de cada columna.
# Por último, sumar los nulos de cada columna

# 3. Imputación (fillna) de nulos
# Anteriormente, hemos visto que la unica variable numerica que tiene no nulos es Age
df_completo = df.copy()

median_Age = df_completo['Age'].median()          # devuelve el valor 28.0
df_completo['Age'] = df_completo['Age'].fillna(median_Age)
df_completo

"""Como la mayoría de los algoritmos de Machine Learning no funcionan correctamente si reciben valores NaN como entrada, es necesario tratarlos previamente.

 Tal como se solicitó en el reto, hemos completado los NaN mediante imputación estadística simple, reemplazando los valores faltantes con un valor central de la distribución; en nuestro caso, utilizamos la mediana.

A partir de ahora, procederemos a trabajar con df_copia.

### 4. Estadística Descriptiva
Utiliza la función `describe()` para obtener un resumen de las variables numéricas (media, desviación estándar, mínimos y máximos).

**Pregunta de análisis:** ¿Notas alguna columna con una desviación estándar (`std`) muy alta o valores máximos (`max`) extraños?
"""

# Trabajaremos sobre las variables cuantitativas
df_cuantitativo = df_completo[['Age','SibSp','Parch','Fare']]
df_cuantitativo.describe().T[['mean','std','min','max']]

"""La elevada desviación típica en la variable Fare evidencia una profunda brecha socioeconómica entre los pasajeros.

Estadísticamente, el valor máximo actúa como una anomalía (outlier), ya que se aleja drásticamente del comportamiento promedio, representando a un grupo selecto de la élite que viajaba en condiciones de lujo extremo.

### 5. Análisis de Variables Categóricas (Object)
Selecciona una columna de tipo texto (categórica) y cuenta cuántas veces aparece cada valor único (frecuencia).
*Pista: Usa `value_counts()`*
"""

# Seleccionamos la variable survived que representa la supervivencia del pasajero
df_categorica = df_completo['Survived']
df_categorica.value_counts()

"""### 6. Conclusiones del Análisis
Escribe aquí un breve párrafo resumiendo qué descubriste sobre el dataset:
* ¿Estaban los datos muy sucios?
* ¿Cuál es la variable con mayor dispersión?
* ¿Qué patrones iniciales observas?

- El principal inconveniente reside en la falta de documentación sobre la edad y la asignación de camarotes. Esto resulta coherente dado el elevado número de víctimas y la pérdida de registros tras el trágico hundimiento del navío. Por lo demás, el conjunto de datos destaca por su limpieza, al no presentar registros duplicados.

   - La variable con mayor dispersión es fare, lo cual resulta una evidencia sobre la diferencia económica entre los pasajeros.

   - Se observa un sesgo de edad, situando al pasajero promedio entre los 28-30 años.

     La falta de información sobre la cabina es un indicador de que el pasajero probablemente pertenecía a las clases bajas o a la tripulación con menor rango. Por ello, existe una correlación directa entre los valores nulos y la clase social: mientras que la ubicación de los pasajeros de primera clase estaba  documentada, los registros de tercera clase eran escasos o desaparecieron en el naufragio.

# Parte 2. Ejercicios extras. (COMPLETAMENTE OPCIONAL, SOLO SE EVALUA LO ANTERIOR)

## Extra 1: Filtrado de Datos

Crea un nuevo DataFrame llamado `df_sobrevivientes` que contenga solo a los pasajeros que sobrevivieron (`Survived == 1`) y muestra cuántos son.
"""

df_sobrevivientes = df[df['Survived'] == 1]
df_sobrevivientes.shape

"""## Extra 2: Agrupación

Calcula el precio promedio del ticket (`Fare`) por cada clase (`Pclass`). ¿Es la primera clase significativamente más cara?
"""

df.groupby('Pclass')['Fare'].mean()

"""Destacamos que el costo de un pasaje de primera clase es el triple que uno de segunda y, por ende, considerablemente más elevado que un ticket de tercera.

# Extra 3: Visualización Básica

Crea un histograma simple para ver la distribución de las edades de todos los pasajeros.
"""

sns.histplot(df['Age'], bins=25, color='skyblue', kde=True)       # Creamos el histograma

plt.title('Distribución Pasajeros según Edad (Age)', fontsize=15)
plt.xlabel('Edad', fontsize=12)
plt.ylabel('Frecuencia', fontsize=12)
plt.show()

"""# Extra 4: Creamos nuestra tabla cruzada

Utiliza `pd.crosstab` para ver la relación entre la Clase (`Pclass`) y si sobrevivió o no (`Survived`).
"""

pd.crosstab(df['Pclass'],df['Survived'])

"""# Extra 5: Ingeniería de variables

Crea una nueva columna llamada `FamilySize` que sea la suma de `SibSp` (hermanos/esposos) y `Parch` (padres/hijos) + 1 (el pasajero mismo).
"""

df['FamilySize'] = df['SibSp'] + df['Parch'] + 1
df

"""# Extra 6: Ordenamiento

Muestra los 5 pasajeros que pagaron la tarifa más alta (Fare), ordenando el DataFrame de forma descendente.
"""

df_desc = df.sort_values(by='Fare', ascending=False)
df_desc.head(5)               # Muestra las cinco primeras filas
