import streamlit as st

st.title("Modelización Predictiva y Análisis de Robustez")
st.subheader("Consumo Energético: Proyecciones 2026")

# Sección de Contexto
st.markdown("""
### 📊 Descripción del Proyecto
Este análisis emplea técnicas de **Machine Learning (ML)** sobre series temporales de gasto eléctrico correspondientes a los periodos **2024-2025**. El objetivo es modelar el comportamiento histórico para generar predicciones precisas hacia el año 2026.
""")

# Sección de Robustez con mejores elementos visuales
st.markdown("### 🛡️ Análisis de Robustez del Modelo")
st.write("Para garantizar la fiabilidad de las predicciones, se han implementado los siguientes protocolos de validación:")

# Usar columnas o una lista con mejor formato
st.info("""
1. **Backtesting (2023-2024):** Se entrenó el modelo con datos históricos previos para predecir el año 2025 y comparar los resultados con los datos reales, validando la precisión del algoritmo.
2. **Pruebas con Datos Sintéticos:** Generación de una serie temporal de 10 años para evaluar la estabilidad del modelo a largo plazo y contrastar la coherencia de la predicción 2026.
""")


# --- FUNCIONES DE CARGA DE DATOS ---
def pagina_principal():
    st.title("Modelización Predictiva")
    # -*- coding: utf-8 -*-
"""Análisis_predictivo_electricidad.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KZA14XkUJvytaS9LlcvEEJU7txwodrap

# **Análisis predictivo: Gastos electricidad 2024-2025**
El presente estudio se centrará en el análisis del gasto de electricidad 2024-2025 correspondientes a la empresa pública GSC.

## **Objetivo**
Realizar un **análisis de series temporales** utilizando técnicas de Machine Learning (ML) a partir de los datos de gasto de electricidad correspondientes a los años 2024 y 2025, con el fin de modelar su comportamiento y realizar posibles predicciones.

## **Contextualización: series temporales en Machine Learning**
Una **serie temporal** es un conjunto de datos ordenados cronológicamente, es decir, registrados a lo largo del tiempo. En este contexto, la variable de interés (variable dependiente) suele representarse en el eje vertical y se analiza en función del tiempo, que se sitúa en el eje horizontal.

El **análisis de series temporales** consiste en aplicar técnicas estadísticas con el objetivo de construir un modelo que permita describir, analizar y explicar el comportamiento de la serie a lo largo del tiempo, así como identificar los factores de los que depende.Además, este análisis utiliza los valores observados en el pasado para intentar estimar o predecir el valor futuro de la variable estudiada. Junto con la predicción, también se proporcionan medidas que indican el grado de confianza o incertidumbre asociado a dichas estimaciones.

## **Información**
Cabe destacar que se va a trabajar con los datos del **gasto eléctrico** de la empresa pública GSC. Se desglosará la información en gasto e importe eléctrico mensual de los años 2024 y 2025.

La información del dataset consta de diversos puntos:
1. Consumos de electricidad 2024-2025: Refleja la variación de consumo mensual.

2. Importes de electricidad 2024-2025: Contiene la información de los importes mensuales.

#### **Instalación e importación de librerías**
En primer lugar descargamos el paquete prophet, herramienta diseñada para realizar pronósticos de series temporales (time series forecasting). Posteriormente, se procede a la importación de diversas librerías.
"""

pip install prophet

# ── Manipulación de datos ────────────────────────────────────────────────────
import pandas as pd
import numpy as np

# ── Visualización ─────────────────────────────────────────────────────────────
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
import seaborn as sns

# ── Series temporales (statsmodels) ───────────────────────────────────────────
import statsmodels.api as sm
from statsmodels.tsa.stattools   import adfuller, kpss, acf, pacf
from statsmodels.tsa.seasonal    import seasonal_decompose, STL
from statsmodels.tsa.ar_model    import AutoReg
from statsmodels.tsa.api         import VAR
from statsmodels.graphics.tsaplots import plot_acf, plot_pacf
from statsmodels.stats.diagnostic import acorr_ljungbox
from prophet import Prophet

# ── Métricas de evaluación ────────────────────────────────────────────────────
from sklearn.metrics import mean_absolute_error, mean_squared_error

# ── Configuración global de visualizaciones ───────────────────────────────────
plt.rcParams['figure.figsize'] = (12, 5)
plt.rcParams['axes.grid'] = True
plt.rcParams['grid.alpha'] = 0.4

"""# **1. Análisis exploratorio de datos (EDA)**
## **1.1 Carga y preparación de datos**
Se procede a la lectura de los archivos en formato **CSV**, tras lo cual se reestructura el dataset según el esquema requerido. Cabe señalar que, aunque el formato **XLSX** sería técnicamente compatible, se ha priorizado el uso de CSV para garantizar la integración con nuestra página web, dado que es el único formato admitido por el sistema.
"""

df_importes = pd.read_csv('importes2425.csv')
df_consumos = pd.read_csv('Consumos2425.csv')

# Preparación del dataset a trabajar
df_pred_imput = df_consumos.melt(id_vars=['Unnamed: 0'], var_name='mes', value_name= 'consumo')
df_pred2 = df_importes.melt(id_vars=['Unnamed: 0'], var_name='mes', value_name= 'importe')
df_pred = pd.merge(df_pred_imput, df_pred2, on=['Unnamed: 0', 'mes'])  # se unifican

# Separación de plantas y año
df_pred[['planta', 'año']] = df_pred['Unnamed: 0'].str.extract(r'(.+)\s(\d{4})')

# Fechas
meses = {
        'enero': 1, 'febrero': 2, 'marzo': 3, 'abril': 4, 'mayo': 5, 'junio': 6,
        'julio': 7, 'agosto': 8, 'septiembre': 9, 'octubre': 10, 'noviembre': 11, 'diciembre': 12
    }
df_pred['mes_num'] = df_pred['mes'].str.lower().map(meses)

# Crear columna de fecha (ds) requerida por Prophet
df_pred['fecha'] = pd.to_datetime(df_pred['año'] + '-' + df_pred['mes_num'].astype(str) + '-01')

# Se pasa consumo e importe a numérico.
df_pred["consumo"] = (df_pred["consumo"].astype(str).str.replace(".", "", regex=False).str.replace(",", ".", regex=False))
df_pred["importe"] = (df_pred["importe"].astype(str).str.replace(".", "", regex=False).str.replace(",", ".", regex=False))
df_pred["consumo"] = pd.to_numeric(df_pred["consumo"], errors="coerce")
df_pred["importe"] = pd.to_numeric(df_pred["importe"], errors="coerce")

# reorganizo el dataframe
df_pred = df_pred.drop(columns=['Unnamed: 0', 'mes'])  # Eliminamos columnas ya usadas

new_column_order = ['planta', 'consumo', 'importe', 'fecha','mes_num','año']           # reorganizamos
remaining_columns = [col for col in df_pred.columns if col not in new_column_order]
df_pred = df_pred[new_column_order + remaining_columns]

# Dataframe finales
df_pred_imput = df_pred.copy()   # Este se utilizara para imputación de nan
df_pred                     # Este se utiliza sin imputacion

#from google.colab import files                                                  #GUARDAR DATAFRAME EN LOCAL
#df_pred.to_csv('format_long.csv', index=False)                                  # 1. Guardar el DataFrame como CSV temporalmente en el entorno de Colab
#files.download('format_long.csv')

"""## **1.2 Imputación de nulos**
Se observa que la única serie temporal que requiere imputación de valores nulos corresponde a la provincia de Santa Cruz. No obstante, este periodo es puntual y podría estar relacionado con el cierre por reformas de la planta.


Por ello, se decide realizar las predicciones tanto con imputación de los valores nulos como sin ella, con el objetivo de evaluar el impacto que esta decisión puede tener en el rendimiento del modelo.

### **Imputación de Valores Faltantes con bfill para 'MAPFRE 1ª' (2024)**

Dado que los valores `NaN` para '**MAPFRE 1ª**' en 2024 se encuentran al inicio del año (los primeros seis meses) y la información válida disponible se encuentra en los meses posteriores, utilizaremos **backward fill** para propagar la primera observación válida hacia atrás y rellenar los NaN´s.
"""

# Realizamos la imputación a la variable df_pred_imput
# Identificar las filas que corresponden a 'MAPFRE 1ª' y el año 2024
mask_mapfre_2024 = (df_pred_imput['planta'] == 'MAPFRE 1ª') & (df_pred_imput['año'] == '2024')

# Aplicar bfill a las columnas 'consumo' e 'importe' solo en esas filas
df_pred_imput.loc[mask_mapfre_2024, 'consumo'] = df_pred_imput.loc[mask_mapfre_2024, 'consumo'].bfill()
df_pred_imput.loc[mask_mapfre_2024, 'importe'] = df_pred_imput.loc[mask_mapfre_2024, 'importe'].bfill()

# Mostrar las filas afectadas para verificar la imputación con bfill
display(df_pred_imput[mask_mapfre_2024])

#from google.colab import files                                                  #GUARDAR DATAFRAME EN LOCAL
#df_pred_imput.to_csv('format_long_imput.csv', index=False)                                  # 1. Guardar el DataFrame como CSV temporalmente en el entorno de Colab
#files.download('format_long_imput.csv')                                               # 2. Descargar el archivo a tu computadora

"""## **1.3 Análisis estadístico clásico de series temporales**

Realizamos un análisis estadístico clásico de series temporales, la **descomposición en tendencia**, **estacionalidad** y **residuos**.
A pesar de que existen herramientas de ML muy potentes, como el Prophet de Meta, que funcionan precisamente descomponiendo la serie en componentes aditivos (tendencia, estacionalidad y festivos) antes de realizar la predicción.

Procedemos a realizar el análisis clásico:
- **Tendencia (tendencia)**: Representa el movimiento o evolución a largo plazo de la serie temporal, una vez eliminados los factores estacionales y el ruido.
- **Estacionalidad (estacionalidad)**: Es un componente cíclico que se repite en el tiempo, normalmente en periodos de corto plazo
. Un ejemplo común es el aumento de pasajeros de avión durante los meses de verano
- **Residuo (residuo)**: Es lo que queda de la serie original tras haber eliminado la tendencia y el componente estacional; básicamente, se calcula por diferencia
"""

# EDA
# Estacionalidad
fig, axes = plt.subplots(nrows=2, ncols=1, figsize=(14, 10), sharex=True)

# Plot para Consumo
sns.lineplot(x='fecha', y='consumo', data=df_pred, ax=axes[0])
axes[0].set_title('Consumo por Fecha')
axes[0].set_ylabel('Consumo')
axes[0].grid(True)

# Plot para Importe
sns.lineplot(x='fecha', y='importe', data=df_pred, ax=axes[1], color='orange')
axes[1].set_title('Importe por Fecha')
axes[1].set_xlabel('Fecha')
axes[1].set_ylabel('Importe')
axes[1].grid(True)

plt.tight_layout()
plt.show()

#correlacion
#4. Análisis de Autocorrelación (ACF)
#El gráfico de Autocorrelación (ACF) mide la correlación entre la serie y sus propios
#valores pasados (lags). Si ves picos significativos en intervalos regulares (por ejemplo, cada 12 meses), tienes una estacionalidad clara.
from statsmodels.graphics.tsaplots import plot_acf

plot_acf(df_pred['consumo'], lags=36)
plot_acf(df_pred['importe'], lags=36)
plt.show()

"""1. El Fenómeno de la Tendencia CrecienteTanto el consumo como el importe muestran una pendiente positiva. El consumo base a finales de 2025 es significativamente mayor que a principios de 2024.Implicación para ML: Un modelo simple (como una media móvil) fallará porque subestimará 2026. Necesitas modelos que manejen bien la tendencia, como Prophet o un ARIMA con integracion ($d=1$).

1. El Fenómeno de la Tendencia CrecienteTanto el consumo como el importe muestran una pendiente positiva. El consumo base a finales de 2025 es significativamente mayor que a principios de 2024.Implicación para ML: Un modelo simple (como una media móvil) fallará porque subestimará 2026. Necesitas modelos que manejen bien la tendencia, como Prophet o un ARIMA con integracion ($d=1$).

esa una de las limitaciones más importantes de Prophet: es un modelo de serie temporal univariante. Esto significa que solo mira el pasado de una variable ($y$) para predecir su futuro, ignorando cómo otras variables (como el importe) influyen en ella en tiempo real.

1. Estacionariedad y TransformaciónAntes de alimentar un modelo, debes saber si las propiedades estadísticas de tu serie cambian en el tiempo.Prueba de Dickey-Fuller Aumentada (ADF): Si tu serie tiene tendencia (no es estacionaria), muchos modelos tradicionales como ARIMA fallarán.Diferenciación: Si no es estacionaria, aplica una diferencia ($y_t - y_{t-1}$) para estabilizar la media.Transformación Logarítmica: Si la varianza aumenta con el tiempo (heterocedasticidad), aplicar log ayuda a normalizarla.

## **3 3. División de Datos (Time Series Split)**
Para dividir los datos en una serie temporal, es fundamental no usar una división aleatoria (como el **train_test_split** tradicional de Scikit-Learn con shuffle=True). En **series de tiempo**, el orden cronológico es sagrado pues el pasado entrena al modelo para predecir el futuro.


Los datos preceden hasta diciembre de 2025, una división lógica sería usar el 80% inicial para entrenamiento y el 20% final para test (validación), lo que nos permitirá evaluar qué tan bien se comporta el modelo antes de lanzarlo a ciegas al 2026.
"""

# Corte en Julio 2025. Esto nos deja 18 meses para entrenar y 6 meses para testear
fecha_corte = '2025-07-01'

# Split for df_pred (sin imputation)
train = df_pred[df_pred['fecha'] < fecha_corte].copy()
test = df_pred[df_pred['fecha'] >= fecha_corte].copy()

# Split for  (con imputation)
train_imput = df_pred_imput[df_pred_imput['fecha'] < fecha_corte].copy()
test_imput = df_pred_imput[df_pred_imput['fecha'] >= fecha_corte].copy()

# Separamos las variables predictoras (X) del objetivo (y)
predictoras = ['importe','fecha','mes_num', 'año']
objetivo = 'consumo'

X_train = train[predictoras]
y_train = train[objetivo]
X_test = test[predictoras]
y_test = test[objetivo]

X_train_imput = train_imput[predictoras]
y_train_imput = train_imput[objetivo]
X_test_imput = test_imput[predictoras]
y_test_imput = test_imput[objetivo]

# Guardar splits
print(f"Registros para entrenamiento (df_pred): {len(X_train)}")
print(f"Registros para evaluación (test df_pred): {len(X_test)}")
print(f"Registros para entrenamiento (df_pred_imput): {len(X_train_imput)}")
print(f"Registros para evaluación (test df_pred_imput): {len(X_test_imput)}")

# Guardar splitstrain.to_csv("01_train_original.csv", index=False)

test.to_csv("02_test_original.csv", index=False)
train_imput.to_csv("03_train_imputado.csv", index=False)
test_imput.to_csv("04_test_imputado.csv", index=False)

"""- En Prophet también se puede usar lavalidación cruzada temporal con horizon, initial y period, que permite evaluar varios cortes históricos en lugar de un solo split.

## **4. Modelo Prophet de Meta**
Dependiendo de la complejidad detectada en el análisis de ruido y tendencia. En nuestro caso, utilizaremos **Prophet de Meta**, este es excelente si existe mucha estacionalidad y huecos en los datos (missing values).


Es muy robusto ante datos faltantes y valores atípicos (outliers). Gestiona la estacionalidad de forma automática sin necesidad de crear tantos lags manuales. Es excelente para explicar a los interesados qué parte del consumo es "tendencia" y qué parte es "estacionalidad". A veces es demasiado "suave" y puede ignorar cambios bruscos de corto plazo que un modelo de boosting sí captaría.

1. ***Estructura de los Datos (Obligatorio)***
Se debe exigir que el formato sea:

- ds: La columna de tiempo. Debe estar en formato YYYY-MM-DD o YYYY-MM-DD HH:MM:SS.
- y: La variable numérica que quieres predecir.


2. ***Estacionalidad y Tendencia***
Prophet asume que tu serie temporal es una combinación de una tendencia general y ciclos repetitivos (estacionalidad). Funciona mejor con datos que tienen ciclos claros (diarios, semanales, anuales).Para detectar estacionalidad anual, idealmente necesitas al menos dos años de datos históricos.

3. ***Valores Atípicos (Outliers)***
Aquí es donde Prophet es un poco "mágico". A diferencia de ARIMA, no necesitas eliminar los datos faltantes (puede manejarlos bien), pero los outliers sí pueden confundir la tendencia.
Si tienes un evento extraño (como una caída de ventas por un fallo en el servidor), es mejor eliminar esos puntos o marcarlos como "festivos" para que el modelo no intente aprender de ellos como si fueran normales.

4. ***¿Estacionariedad? (No es necesaria)***
Esta es la gran ventaja. En modelos clásicos, debes aplicar logaritmos o diferenciación para que la media y la varianza sean constantes (hacer la serie "estacionaria").Prophet no lo requiere. Puede manejar tendencias crecientes o decrecientes de forma nativa mediante regresión aditiva o multiplicativa.

## **Pasos**


1. ***Modelo base*** : Se utiliza Prophet considerando únicamente la fecha (ds) y el consumo (y). El modelo se encarga de identificar automáticamente la tendencia y las estacionalidades presentes en los datos (diaria, semanal y anual). Además, se diferenciarán los casos en los que se han imputado los datos de la Planta 1 de Mapfre de aquellos en los que no se ha realizado imputación. Además de realizar una prediccion del consumo y el importe.
---
## **Función principal modelar una planta**
Dado que Prophet requiere que los regresores (las features) estén presentes tanto en el entrenamiento como en la predicción de prueba, el código debe filtrar por planta dentro de tus conjuntos ya divididos.

Aquí tienes el script optimizado para entrenar con tus variables y validar con el set de test:
"""

def analizar_planta(planta_nombre, train_planta, test_planta, variable, imput=False):
    """Entrena Prophet y evalúa rendimiento"""
    if len(train_planta) < 6 or len(test_planta) == 0:
        return None, {}

    # Preparar datos Prophet (solo fecha y variable objetivo)
    train_prophet = train_planta[["fecha", variable]].dropna()
    test_prophet = test_planta[["fecha", variable]].dropna()

    train_prophet = train_prophet.rename(columns={"fecha": "ds", variable: "y"})
    test_prophet = test_prophet.rename(columns={"fecha": "ds", variable: "y"})

    # Modelo Prophet para datos mensuales
    model = Prophet(
        yearly_seasonality=True,
        seasonality_mode='multiplicative',
        changepoint_prior_scale=0.05
    )

    model.fit(train_prophet)

    # Predicción test
    future = model.make_future_dataframe(periods=len(test_planta), freq='MS')
    forecast = model.predict(future)

    # Evaluación
    pred_test = forecast[forecast['ds'].isin(test_prophet['ds'])][['ds', 'yhat']]
    resultados = test_prophet.merge(pred_test, on='ds')

    if len(resultados) > 0:
        mae = mean_absolute_error(resultados['y'], resultados['yhat'])
        mape = np.mean(np.abs((resultados['y'] - resultados['yhat']) / resultados['y'])) * 100
        return model, {'mae': mae, 'mape': mape, 'n_test': len(test_planta)}

    return None, {}

"""
## **ANÁLISIS COMPLETO (NO IMPUTADO vs IMPUTADO)**
"""

resultados = {"original": {"consumo": {}, "importe": {}},
              "imputado": {"consumo": {}, "importe": {}}}
pronosticos_anuales_2026 = [] # Stores yearly sums for each scenario

# New list to collect all monthly prediction dataframes for merging later
all_individual_monthly_forecasts = []

plantas = sorted(df_pred["planta"].unique())

for planta in plantas:
    print(f"   {planta}...", end=" ")

    # Datos por planta
    train_p = train[train["planta"] == planta]
    test_p = test[test["planta"] == planta]

    train_p_i = train_imput[train_imput["planta"] == planta]
    test_p_i = test_imput[test_imput["planta"] == planta]

    # ORIGINAL - Consumo
    model_orig_cons, metrics_orig_cons = analizar_planta(planta, train_p, test_p, "consumo", imput=False)
    if model_orig_cons:
        resultados["original"]["consumo"][planta] = metrics_orig_cons

        futuro_cons = model_orig_cons.make_future_dataframe(periods=18, freq="MS") # 18 periods to cover all of 2026
        forecast_cons = model_orig_cons.predict(futuro_cons)
        forecast_cons_2026 = forecast_cons[forecast_cons['ds'].dt.year == 2026] # Filter for 2026
        cons_2026 = forecast_cons_2026["yhat"].sum()

        pronosticos_anuales_2026.append({"planta": planta, "tipo": "orig_cons", "prom_2026": cons_2026})

        # Prepare monthly predictions for this scenario
        temp_df = forecast_cons_2026[['ds', 'yhat']].copy()
        temp_df['planta'] = planta
        temp_df['tipo_pred'] = 'orig_cons_pred'
        temp_df['mes'] = temp_df['ds'].dt.strftime('%b %Y')
        temp_df.rename(columns={'yhat': 'valor_predicho'}, inplace=True)
        all_individual_monthly_forecasts.append(temp_df)
        print("✓oC", end="")

    # ORIGINAL - Importe
    model_orig_imp, metrics_orig_imp = analizar_planta(planta, train_p, test_p, "importe", imput=False)
    if model_orig_imp:
        resultados["original"]["importe"][planta] = metrics_orig_imp

        future_orig_imp = model_orig_imp.make_future_dataframe(periods=18, freq="MS") # 18 periods to cover all of 2026
        forecast_orig_imp = model_orig_imp.predict(future_orig_imp)
        forecast_orig_imp_2026 = forecast_orig_imp[forecast_orig_imp['ds'].dt.year == 2026] # Filter for 2026
        imp_2026 = forecast_orig_imp_2026["yhat"].sum()

        pronosticos_anuales_2026.append({"planta": planta, "tipo": "orig_imp", "prom_2026": imp_2026})

        # Prepare monthly predictions for this scenario
        temp_df = forecast_orig_imp_2026[['ds', 'yhat']].copy()
        temp_df['planta'] = planta
        temp_df['tipo_pred'] = 'orig_imp_pred'
        temp_df['mes'] = temp_df['ds'].dt.strftime('%b %Y')
        temp_df.rename(columns={'yhat': 'valor_predicho'}, inplace=True)
        all_individual_monthly_forecasts.append(temp_df)
        print("✓oI", end="")

    # IMPUTADO - Consumo
    model_imp_cons, metrics_imp_cons = analizar_planta(planta, train_p_i, test_p_i, "consumo", imput=True)
    if model_imp_cons:
        resultados["imputado"]["consumo"][planta] = metrics_imp_cons

        future_imp_cons = model_imp_cons.make_future_dataframe(periods=18, freq="MS") # 18 periods to cover all of 2026
        forecast_imp_cons = model_imp_cons.predict(future_imp_cons)
        forecast_imp_cons_2026 = forecast_imp_cons[forecast_imp_cons['ds'].dt.year == 2026] # Filter for 2026
        cons_2026_i = forecast_imp_cons_2026["yhat"].sum()

        pronosticos_anuales_2026.append({"planta": planta, "tipo": "imp_cons", "prom_2026": cons_2026_i})

        # Prepare monthly predictions for this scenario
        temp_df = forecast_imp_cons_2026[['ds', 'yhat']].copy()
        temp_df['planta'] = planta
        temp_df['tipo_pred'] = 'imp_cons_pred'
        temp_df['mes'] = temp_df['ds'].dt.strftime('%b %Y')
        temp_df.rename(columns={'yhat': 'valor_predicho'}, inplace=True)
        all_individual_monthly_forecasts.append(temp_df)
        print("✓iC", end="")

    # IMPUTADO - Importe
    model_imp_imp, metrics_imp_imp = analizar_planta(planta, train_p_i, test_p_i, "importe", imput=True)
    if model_imp_imp:
        resultados["imputado"]["importe"][planta] = metrics_imp_imp

        future_imp_imp = model_imp_imp.make_future_dataframe(periods=18, freq="MS") # 18 periods to cover all of 2026
        forecast_imp_imp = model_imp_imp.predict(future_imp_imp)
        forecast_imp_imp_2026 = forecast_imp_imp[forecast_imp_imp['ds'].dt.year == 2026] # Filter for 2026
        imp_2026_i = forecast_imp_imp_2026["yhat"].sum()

        pronosticos_anuales_2026.append({"planta": planta, "tipo": "imp_imp", "prom_2026": imp_2026_i})

        # Prepare monthly predictions for this scenario
        temp_df = forecast_imp_imp_2026[['ds', 'yhat']].copy()
        temp_df['planta'] = planta
        temp_df['tipo_pred'] = 'imp_imp_pred'
        temp_df['mes'] = temp_df['ds'].dt.strftime('%b %Y')
        temp_df.rename(columns={'yhat': 'valor_predicho'}, inplace=True)
        all_individual_monthly_forecasts.append(temp_df)
        print("✓iI")
    else:
        print("✗")

print("\n✅ Modelado completado")

# --- Combine all monthly forecasts into a single DataFrame ---
if all_individual_monthly_forecasts:
    df_all_monthly_forecasts_long = pd.concat(all_individual_monthly_forecasts, ignore_index=True)

    # Pivot the table to get prediction types as columns
    df_pronosticos_mensuales_2026 = df_all_monthly_forecasts_long.pivot_table(
        index=['planta', 'ds', 'mes'], # Include mes in index
        columns='tipo_pred',
        values='valor_predicho'
    ).reset_index()

    # Reorder columns for better readability
    cols = ['planta', 'ds', 'mes', 'orig_cons_pred', 'orig_imp_pred', 'imp_cons_pred', 'imp_imp_pred']
    df_pronosticos_mensuales_2026 = df_pronosticos_mensuales_2026.reindex(columns=cols)
else:
    df_pronosticos_mensuales_2026 = pd.DataFrame()

# Display the head of the new DataFrame for confirmation
display(df_pronosticos_mensuales_2026)

# Guardar
df_pronosticos_mensuales_2026.to_csv("prediccion2026.csv", index=False)

"""###  Tabla comparativa de resultados.

Aquí combinamos el DataFrame `df_pred` (que contiene los datos históricos de consumo hasta 2025) con las predicciones para 2026 (`final_predictions_2026`) en un nuevo DataFrame llamado `df_predic`. Esto nos permite tener una serie temporal completa que incluye tanto el pasado como el futuro predicho.
"""

print("\n 5. RESULTADOS")

tabla = []
for planta in plantas:
    for dataset in ['original', 'imputado']:
        cons = resultados[dataset]['consumo'].get(planta, {})
        imp = resultados[dataset]['importe'].get(planta, {})


        tabla.append({
            'Planta': planta,
            'Dataset': dataset.upper(),
            'Test_C': cons.get('n_test', 0),
            'MAPE_C%': f"{cons.get('mape', 0):.1f}",
            'MAE_C': f"{cons.get('mae', 0):,.0f}",
            'MAPE_I%': f"{imp.get('mape', 0):.1f}",
            'MAE_I': f"{imp.get('mae', 0):,.0f}"
        })
    # Linea en blanco
    tabla.append({
        'Planta': '', 'Dataset': '', 'Test_C': '', 'MAPE_C%': '',
        'MAE_C': '', 'MAPE_I%': '', 'MAE_I': ''
    })

df_validacion = pd.DataFrame(tabla)

#Eliminar ultima linea blanca si hay
if not df_validacion.empty and df_validacion.iloc[-1]['Planta'] == '':
    df_validacion = df_validacion.iloc[:-1]

print(df_validacion.to_string(index=False))
print()

"""## **Pronóstico 2026 y guardado**"""

print("\n 5. PRONÓSTICO 2026")

df_pronosticos = pd.DataFrame(pronosticos_2026)
pivot_pron = df_pronosticos.pivot(index="planta", columns="tipo", values="prom_2026")
print(pivot_pron.round(0).astype(int).to_string())

# Guardar todo
df_validacion.to_csv("05_resultados_comparacion.csv", index=False)
df_pronosticos.to_csv("06_pronosticos_2026.csv", index=False)

print(f"\n MEJOR PRECISIÓN (menor MAPE consumo):")
# Filter out rows where 'MAPE_C%' is an empty string before converting to float
mejor = df_validacion[df_validacion['MAPE_C%'] != ''].loc[df_validacion[df_validacion['MAPE_C%'] != '']['MAPE_C%'].astype(float).idxmin()]
print(f"   {mejor['Planta']} {mejor['Dataset']} → MAPE {mejor['MAPE_C%']}%\n")


print(" ¡ANÁLISIS COMPLETO TERMINADO!")
print("Archivos generados:")
print("   01_train_original.csv")
print("   02_test_original.csv")
print("   03_train_imputado.csv")
print("   04_test_imputado.csv")
print("   05_resultados_comparacion.csv")
print("   06_pronosticos_2026.csv")

from google.colab import files
files.download("06_pronosticos_2026.csv")

"""EXTRA: Realizamos evaluación sin generar una division de datos.

"""

# Python
from prophet.diagnostics import cross_validation
df_cv = cross_validation(m, initial='730 days', period='180 days', horizon = '365 days')

# Python
df_cv.head()

# Python
cutoffs = pd.to_datetime(['2013-02-15', '2013-08-15', '2014-02-15'])
df_cv2 = cross_validation(m, cutoffs=cutoffs, horizon='365 days')

# Python
from prophet.diagnostics import performance_metrics
df_p = performance_metrics(df_cv)
df_p.head()

# Python
from prophet.diagnostics import register_performance_metric, rolling_mean_by_h
import numpy as np
@register_performance_metric
def mase(df, w):
    """Mean absolute scale error

        Parameters
        ----------
        df: Cross-validation results dataframe.
        w: Aggregation window size.

        Returns
        -------
        Dataframe with columns horizon and mase.
    """
    e = (df['y'] - df['yhat'])
    d = np.abs(np.diff(df['y'])).sum()/(df['y'].shape[0]-1)
    se = np.abs(e/d)
    if w < 0:
        return pd.DataFrame({'horizon': df['horizon'], 'mase': se})
    return rolling_mean_by_h(
        x=se.values, h=df['horizon'].values, w=w, name='mase'
    )

df_mase = performance_metrics(df_cv, metrics=['mase'])
df_mase.head()

# Python
from prophet.plot import plot_cross_validation_metric
fig = plot_cross_validation_metric(df_cv, metric='mape')

"""## **Evaluación de Métricas**
Para saber si tu predicción es buena, no uses el $R^2$ común. Usa métricas de error de magnitud:
- **MAE (Error Absoluto Medio):** Cuánto te equivocas de media en unidades reales (ej: euros o kWh).
- **RMSE (Raíz del Error Cuadrático Medio)**: Penaliza más los errores grandes.
- **MAPE (Error Porcentual Absoluto Medio)**: Útil para explicar a negocio ("Fallamos un 5% en la predicción").


Ademas añadimos las metricas
"""
    
def visualizar_datos():
    st.title("Análisis de Robustez")
    st.write("Carga un archivo CSV para visualizar los datos.")
    archivo_cargado = st.file_uploader("Elige un archivo CSV", type="csv")

    if archivo_cargado is not None:
        df = pd.read_csv(archivo_cargado)
        st.write("Datos del archivo csv:")
        st.write(df)
        st.write("Estadísticas descriptivas")
        st.write(df.describe())

# menu para llamar a la funcion
st.sidebar.title("Navegación")
pagina1 = st.sidebar.selectbox("Selecciona una página", ["Página Principal", 
                                                        "Visualización de Datos"])
if pagina1 == "Página Principal":
    pagina_principal()
elif pagina1 == "Visualización de Datos":
    visualizar_datos()
